[package]
name = "git-melt"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
glob = "0.3.3"
ignore = "0.4.25"

[dev-dependencies]
tempfile = "3.24.0"
